// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-matters.ts
import { defineTool, ToolError } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.97.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find(
          (v) => typeof v === "string" && v.trim().startsWith("sb_publishable_")
        )?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error(
    "SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required"
  );
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-matters.ts
var list_matters_default = defineTool({
  name: "list_matters",
  title: "List matters",
  description: "List eviction and collection matters visible to the signed-in user.",
  inputSchema: {
    status: z.enum(["intake", "notice_preparation", "notice_served", "waiting_period", "ready_to_file", "filed", "court_scheduled", "in_court_process", "outcome_pending", "resolved", "closed", "on_hold", "draft", "attorney_review"]).optional().describe("Filter by case status."),
    matter_type: z.enum(["non_payment", "holdover", "lease_violation", "former_tenant_collection", "judgment_collection", "other"]).optional().describe("Filter by matter type."),
    limit: z.number().int().min(1).max(50).optional().describe("Max results to return (default 20)."),
    offset: z.number().int().min(0).optional().describe("Offset for pagination (default 0).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, matter_type, limit = 20, offset = 0 }, ctx) => {
    if (!ctx.isAuthenticated()) {
      throw new ToolError("Not authenticated", { isError: true });
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("cases").select("id, case_number, status, matter_type, opened_date, closed_date, priority, sub_status, clients(id, company_name)").order("opened_date", { ascending: false }).range(offset, offset + limit - 1);
    if (status) query = query.eq("status", status);
    if (matter_type) query = query.eq("matter_type", matter_type);
    const { data, error } = await query;
    if (error) {
      throw new ToolError(error.message, { isError: true });
    }
    return {
      content: [
        {
          type: "text",
          text: `Found ${data?.length ?? 0} matter(s).`
        }
      ],
      structuredContent: { matters: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-matter-summary.ts
import { defineTool as defineTool2, ToolError as ToolError2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var get_matter_summary_default = defineTool2({
  name: "get_matter_summary",
  title: "Get matter summary",
  description: "Return a single matter's header, status, matter type, and current balance.",
  inputSchema: {
    case_id: z2.string().uuid().describe("The case/matter UUID.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ case_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      throw new ToolError2("Not authenticated", { isError: true });
    }
    const supabase = supabaseForUser(ctx);
    const { data: matter, error: matterError } = await supabase.from("cases").select(
      "id, case_number, status, matter_type, opened_date, closed_date, priority, sub_status, is_on_hold, hold_reason, court_name, court_case_number, court_address, clients(id, company_name), properties(address_line1, city, state, zip), tenants(full_name)"
    ).eq("id", case_id).single();
    if (matterError) {
      throw new ToolError2(matterError.message, { isError: true });
    }
    const { data: tenant, error: tenantError } = await supabase.from("case_tenants").select("tenants(full_name)").eq("case_id", case_id).eq("is_primary", true).single();
    if (tenantError && tenantError.code !== "PGRST116") {
    }
    const { data: balance, error: balanceError } = await supabase.rpc("ledger_balance_as_of", { p_case_id: case_id, p_as_of: (/* @__PURE__ */ new Date()).toISOString() });
    if (balanceError) {
    }
    return {
      content: [
        {
          type: "text",
          text: `Matter ${matter.case_number} is ${matter.status}.`
        }
      ],
      structuredContent: {
        matter,
        primary_tenant: tenant?.tenants ?? null,
        balance_due: balance ?? null
      }
    };
  }
});

// src/lib/mcp/tools/list-matter-events.ts
import { defineTool as defineTool3, ToolError as ToolError3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var list_matter_events_default = defineTool3({
  name: "list_matter_events",
  title: "List matter events",
  description: "Return the chronological timeline/events for a single matter.",
  inputSchema: {
    case_id: z3.string().uuid().describe("The case/matter UUID."),
    limit: z3.number().int().min(1).max(50).optional().describe("Max events to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ case_id, limit = 20 }, ctx) => {
    if (!ctx.isAuthenticated()) {
      throw new ToolError3("Not authenticated", { isError: true });
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("matter_events").select("id, event_type, event_at, description, metadata, created_by, created_at").eq("case_id", case_id).order("event_at", { ascending: false }).limit(limit);
    if (error) {
      throw new ToolError3(error.message, { isError: true });
    }
    return {
      content: [{ type: "text", text: `Found ${data?.length ?? 0} event(s).` }],
      structuredContent: { events: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-matter-documents.ts
import { defineTool as defineTool4, ToolError as ToolError4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^3.25.76";
var list_matter_documents_default = defineTool4({
  name: "list_matter_documents",
  title: "List matter documents",
  description: "List documents for a matter. For admin users all documents are returned; for client users only client-visible documents are returned.",
  inputSchema: {
    case_id: z4.string().uuid().describe("The case/matter UUID."),
    category: z4.enum(["lease", "rent_ledger", "notice", "proof_of_service", "petition_filing", "court_document", "photo", "correspondence", "other"]).optional().describe("Filter by document category."),
    limit: z4.number().int().min(1).max(50).optional().describe("Max documents to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ case_id, category, limit = 20 }, ctx) => {
    if (!ctx.isAuthenticated()) {
      throw new ToolError4("Not authenticated", { isError: true });
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("documents").select("id, file_name, category, mime_type, file_size, visible_to_client, description, created_at, uploaded_by").eq("case_id", case_id).order("created_at", { ascending: false }).limit(limit);
    if (category) query = query.eq("category", category);
    const { data, error } = await query;
    if (error) {
      throw new ToolError4(error.message, { isError: true });
    }
    return {
      content: [{ type: "text", text: `Found ${data?.length ?? 0} document(s).` }],
      structuredContent: { documents: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-court-events.ts
import { defineTool as defineTool5, ToolError as ToolError5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z5 } from "npm:zod@^3.25.76";
var list_court_events_default = defineTool5({
  name: "list_court_events",
  title: "List court events",
  description: "Return upcoming court events for the signed-in user's scope.",
  inputSchema: {
    case_id: z5.string().uuid().optional().describe("Optional case/matter UUID to restrict events."),
    from: z5.string().datetime().optional().describe("Optional ISO start date (default now)."),
    limit: z5.number().int().min(1).max(50).optional().describe("Max events to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ case_id, from, limit = 20 }, ctx) => {
    if (!ctx.isAuthenticated()) {
      throw new ToolError5("Not authenticated", { isError: true });
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("court_events").select("id, case_id, event_type, start_at, end_at, court_name, location, virtual_link, outcome, next_event_at, notes").order("start_at", { ascending: true }).limit(limit);
    if (case_id) query = query.eq("case_id", case_id);
    if (from) query = query.gte("start_at", from);
    else query = query.gte("start_at", (/* @__PURE__ */ new Date()).toISOString());
    const { data, error } = await query;
    if (error) {
      throw new ToolError5(error.message, { isError: true });
    }
    return {
      content: [{ type: "text", text: `Found ${data?.length ?? 0} court event(s).` }],
      structuredContent: { court_events: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-notifications.ts
import { defineTool as defineTool6, ToolError as ToolError6 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z6 } from "npm:zod@^3.25.76";
var list_notifications_default = defineTool6({
  name: "list_notifications",
  title: "List notifications",
  description: "Return unread in-app notifications for the signed-in user.",
  inputSchema: {
    status: z6.enum(["queued", "sent", "failed", "read"]).optional().describe("Filter by notification status (default sent)."),
    limit: z6.number().int().min(1).max(50).optional().describe("Max notifications to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit = 20 }, ctx) => {
    if (!ctx.isAuthenticated()) {
      throw new ToolError6("Not authenticated", { isError: true });
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("notifications").select("id, case_id, title, message, channel, status, read_at, created_at").eq("recipient_user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit);
    if (status) query = query.eq("status", status);
    else query = query.eq("status", "sent");
    const { data, error } = await query;
    if (error) {
      throw new ToolError6(error.message, { isError: true });
    }
    return {
      content: [{ type: "text", text: `Found ${data?.length ?? 0} notification(s).` }],
      structuredContent: { notifications: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-collection-matters.ts
import { defineTool as defineTool7, ToolError as ToolError7 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z7 } from "npm:zod@^3.25.76";
var list_collection_matters_default = defineTool7({
  name: "list_collection_matters",
  title: "List collection matters",
  description: "Return collection/debt matters visible to the signed-in user.",
  inputSchema: {
    status: z7.enum(["open", "in_house", "placed_with_agency", "judgment_sold", "in_enforcement", "settled", "written_off", "paid"]).optional().describe("Filter by collection status."),
    limit: z7.number().int().min(1).max(50).optional().describe("Max results to return (default 20)."),
    offset: z7.number().int().min(0).optional().describe("Offset for pagination (default 0).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit = 20, offset = 0 }, ctx) => {
    if (!ctx.isAuthenticated()) {
      throw new ToolError7("Not authenticated", { isError: true });
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("collection_matters").select("id, case_id, status, origin, total_owed, total_paid, balance_due, created_at, clients(id, company_name), cases(case_number)").order("created_at", { ascending: false }).range(offset, offset + limit - 1);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) {
      throw new ToolError7(error.message, { isError: true });
    }
    return {
      content: [{ type: "text", text: `Found ${data?.length ?? 0} collection matter(s).` }],
      structuredContent: { collection_matters: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-collection-balance.ts
import { defineTool as defineTool8, ToolError as ToolError8 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z8 } from "npm:zod@^3.25.76";
var get_collection_balance_default = defineTool8({
  name: "get_collection_balance",
  title: "Get collection balance",
  description: "Return the current balance and recent activity for a collection matter.",
  inputSchema: {
    collection_matter_id: z8.string().uuid().describe("The collection matter UUID.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ collection_matter_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      throw new ToolError8("Not authenticated", { isError: true });
    }
    const supabase = supabaseForUser(ctx);
    const { data: matter, error: matterError } = await supabase.from("collection_matters").select("id, case_id, status, origin, total_owed, total_paid, balance_due, created_at, cases(case_number)").eq("id", collection_matter_id).single();
    if (matterError) {
      throw new ToolError8(matterError.message, { isError: true });
    }
    const { data: activities, error: activitiesError } = await supabase.from("collection_activities").select("id, activity_type, amount, activity_date, description, created_at").eq("collection_matter_id", collection_matter_id).order("activity_date", { ascending: false }).limit(20);
    if (activitiesError) {
    }
    return {
      content: [{ type: "text", text: `Collection matter balance is ${matter.balance_due}.` }],
      structuredContent: {
        collection_matter: matter,
        recent_activities: activities ?? []
      }
    };
  }
});

// src/lib/mcp/tools/log-client-update.ts
import { defineTool as defineTool9, ToolError as ToolError9 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z9 } from "npm:zod@^3.25.76";
var log_client_update_default = defineTool9({
  name: "log_client_update",
  title: "Log client update",
  description: "Post a client-visible update note on a matter and notify the client. Admin-only.",
  inputSchema: {
    case_id: z9.string().uuid().describe("The case/matter UUID."),
    content: z9.string().min(1).max(2e3).describe("The client-facing update message.")
  },
  annotations: { readOnlyHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ case_id, content }, ctx) => {
    if (!ctx.isAuthenticated()) {
      throw new ToolError9("Not authenticated", { isError: true });
    }
    const supabase = supabaseForUser(ctx);
    const { data: profile, error: profileError } = await supabase.from("profiles").select("id").eq("id", ctx.getUserId()).single();
    if (profileError || !profile) {
      throw new ToolError9("Unable to verify caller profile", { isError: true });
    }
    const { data: roles } = await supabase.from("user_roles").select("role").eq("user_id", ctx.getUserId());
    const isAdmin = (roles ?? []).some((r) => r.role === "super_admin" || r.role === "admin");
    if (!isAdmin) {
      throw new ToolError9("Only admin users can log client updates", { isError: true });
    }
    const { data: note, error: noteError } = await supabase.from("case_notes").insert({
      case_id,
      note_type: "client_update",
      content,
      created_by: ctx.getUserId()
    }).select("id, content, created_at").single();
    if (noteError) {
      throw new ToolError9(noteError.message, { isError: true });
    }
    return {
      content: [{ type: "text", text: "Client update logged." }],
      structuredContent: { note }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "fyvwavnyndvyganyknaa";
var mcp_default = defineMcp({
  name: "evict-os",
  title: "Evict OS",
  version: "1.0.0",
  instructions: "Evict OS case management tools. Read-only tools let assistants look up matters, timelines, court events, documents, and collections for the connected user. Admin users may also log client-visible updates.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_matters_default,
    get_matter_summary_default,
    list_matter_events_default,
    list_matter_documents_default,
    list_court_events_default,
    list_notifications_default,
    list_collection_matters_default,
    get_collection_balance_default,
    log_client_update_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
